-- Creacion de categorias
INSERT INTO `categories` VALUES
                             (1,'Conquista cualquier terreno con nuestros vehículos 4x4, diseñados para quienes buscan aventura sin límites. Potentes y resistentes, estos coches te llevarán a lugares inaccesibles, garantizando una conducción cómoda y segura en todo tipo de caminos. Ya sea en montañas, desiertos o caminos de tierra, un 4x4 te ofrece el control necesario para superar cualquier desafío. Perfecto para quienes necesitan un compañero fiel en sus exploraciones más extremas. ¡Atrévete a desafiar los límites con un 4x4!','/imagenes/4x4.jpg','4x4'),
                             (2,'Experimenta el futuro de la conducción con nuestros vehículos eléctricos, diseñados para ofrecerte un rendimiento excepcional mientras cuidas del medio ambiente. Con tecnología de punta, estos coches proporcionan una conducción silenciosa, eficiente y libre de emisiones, sin comprometer la potencia ni la autonomía. Ideales para quienes buscan una conducción limpia, moderna y con estilo, nuestros vehículos eléctricos están aquí para transformar tu experiencia al volante.','/imagenes/electricos.jpg','Electricos'),
                             (3,'Siente la adrenalina al volante de nuestros exclusivos coches deportivos, diseñados para ofrecerte una experiencia de conducción inigualable. Con motores de alto rendimiento, diseño aerodinámico y tecnología de vanguardia, estos vehículos están hechos para los que buscan velocidad y emoción en cada curva. Ya sea en la pista o en la carretera, estos coches te ofrecen un control total y una sensación de libertad absoluta. Atrévete a vivir la velocidad con estilo y precisión.','/imagenes/deportivos.jpg','Deportivos'),
                             (4,'Viaja con comodidad y seguridad en nuestros vehículos familiares, diseñados para acompañarte en cada aventura en familia. Con amplios espacios, tecnología avanzada y características de seguridad excepcionales, nuestros coches familiares ofrecen el equilibrio perfecto entre confort, versatilidad y rendimiento. Ya sea para viajes largos o trayectos urbanos, disfrutarás de una conducción suave y relajante, con el respaldo de una marca que cuida de lo que más importa: tu familia.','/imagenes/familiares.jpg','Familiares'),
                             (5,'Déjate seducir por el lujo y la exclusividad con nuestros vehículos de alta gama. Cada detalle de estos coches está diseñado para brindarte la máxima comodidad y elegancia, desde sus materiales premium hasta sus prestaciones tecnológicas de última generación. Con un diseño sofisticado y una conducción impecable, nuestros coches de lujo son la elección perfecta para aquellos que buscan lo mejor en cada viaje. Disfruta de una experiencia de conducción única, donde la perfección es la norma.','/imagenes/lujo.jpg','Lujo');
-- Creacion de productos
INSERT INTO `products` VALUES
                           (1,'Robusto 4x4 con capacidad todoterreno.',271,'https://scene7.toyota.eu/is/image/toyotaeurope/LCR0012a_24_WEB:Large-Landscape?ts=1712237347791&resMode=sharp2&op_usm=1.75,0.3,2,0&fmt=png-alpha','Toyota',190,'4.0L V6','Toyota Land Cruiser',45000,2,1),
                           (2,'Clásico todoterreno ideal para aventuras.',285,'https://cdn.prod.website-files.com/5ec85520c4dfff034b036be2/65c2a025c92733315983325b_wrangler3.webp','Jeep',180,'3.6L V6','Jeep Wrangler',42000,2,1),
                           (3,'Familiar espacioso con gran capacidad.',190,'https://images.prismic.io/carwow/50be31d1-da22-4d93-a972-7fa00cd51987_LHD+Ford+S-MAX+2020+exterior-05.jpg','Ford',200,'2.0L I4 Turbo','Ford S-Max',32000,1,4),
                           (4,'Familiar versátil con tecnología avanzada.',140,'https://www.km77.com/images/medium/2/6/8/3/renault-grand-scenic-2021-frontal.352683.jpg','Renault',190,'1.3L I4 Turbo','Renault Grand Scenic',30000,1,4),
                           (5,'Eléctrico con autonomía y tecnología avanzada.',450,'https://cdn-drivek-datak.motork.net/configurator-imgs/cars/es/1600/TESLA/MODEL-3/43043_SEDAN-4-DOORS/tesla-model-3-front-view.jpg','Tesla',225,'Eléctrico','Tesla Model 3',50000,3,2),
                           (6,'Compacto eléctrico con cero emisiones.',150,'https://images.forococheselectricos.com/image/l/1320w/wp-content/uploads/2017/11/170905215242-2018-nissan-leaf-front-1024x576.jpg','Nissan',150,'Eléctrico','Nissan Leaf',28000,3,2),
                           (7,'Deportivo icónico con rendimiento superior.',443,'https://www.cnnbrasil.com.br/wp-content/uploads/sites/12/2024/05/Porsche-911-Carrera-2025-Hibrido-16.jpg?w=880','Porsche',305,'3.0L Boxer 6','Porsche 911',100000,2,3),
                           (8,'Deportivo de lujo con diseño exclusivo.',710,'https://cdn.ferrari.com/cms/network/media/img/resize/6094000a8c09a35ca689fba0-ferrari-magazine-S3OmQ-vnzt.jpg','Ferrari',340,'3.9L V8 Turbo','Ferrari F8 Tributo',250000,2,3),
                           (9,'Lujo sin igual con detalles artesanales.',563,'https://www.autonocion.com/wp-content/uploads/2018/11/Mansory-Rolls-Royce-Phantom-2018-25.jpg','Rolls Royce',250,'6.75L V12','Rolls Royce Phantom',450000,3,5),
                           (10,'Lujo y confort en un coupé elegante.',542,'https://hips.hearstapps.com/hmg-prod/images/continental-gt-and-gtc-s-1-1654518508.jpg','Bentley',318,'4.0L V8','Bentley Continental GT',350000,3,5),
                           (11,'Robusto 4x4 ideal para terrenos difíciles.',395,'https://pictures.dealer.com/m/mocrevecoeurlr/0693/7c2016eae6d8fa09798d45758dd00143x.jpg','Land Rover',191,'3.0L I6','Land Rover Defender',55000,2,1),
                           (12,'Fuerza y durabilidad en cualquier terreno.',201,'https://s2.glbimg.com/FK-W1TarrxErVVPZ8HcXczwDzeI=/1200x/smart/filters:cover():strip_icc()/i.s3.glbimg.com/v1/AUTH_cf9d035bf26b4646b105bd958f32089d/internal_photos/bs/2020/U/k/sf737dSDeaSEL2oyQldg/2019-11-18-hiluxmateria.jpg','Toyota',175,'2.8L I4 Turbo Diesel','Toyota Hilux',40000,2,1),
                           (13,'Lujoso todoterreno con capacidad todoterreno insuperable.',577,'http://carlook.net/data/db_photos/mercedes-benz/g-class_amg/w463f_f/mercedes-benz-g-class-amg-w463f_f_suv5d-1917.jpg','Mercedes-Benz',210,'4.0L V8 Turbo','Mercedes-Benz G-Class',130000,2,1),
                           (14,'Un todoterreno versátil con gran capacidad.',271,'https://wallpaperaccess.com/full/2692213.jpg','Jeep',180,'3.2L V6','Jeep Cherokee',45000,2,1),
                           (15,'Familiar espacioso con diseño moderno y eficiencia.',131,'https://images.netdirector.co.uk/gforces-auto/image/upload/q_auto,c_crop,f_auto,fl_lossy,x_1403,y_1307,w_4344,h_2441/auto-client/0b05e4a0f276ccc6c70945a53ee2f221/2961047_kvru6m5i40.jpg','Peugeot',188,'1.2L I3 Turbo','Peugeot 5008',38000,1,4),
                           (16,'Familiar compacto y eficiente con una excelente relación calidad-precio.',150,'https://www.topgear.com/sites/default/files/cars-car/carousel/2016/03/vw_7422.jpg','Volkswagen',200,'1.5L I4 Turbo','Volkswagen Touran',32000,1,4),
                           (17,'Familiar con acabados premium y amplio espacio interior.',272,'https://auto.ironhorse.ru/wp-content/uploads/2015/10/superb-3-lb-fl-front.jpg','Skoda',250,'2.0L I4 Turbo','Skoda Superb',42000,1,4),
                           (18,'SUV familiar espacioso, con alta eficiencia y tecnología avanzada.',190,'https://www.hdcarwallpapers.com/walls/2018_honda_cr_v_4k_3-HD.jpg','Honda',200,'1.5L I4 Turbo','Honda CR-V',35000,1,4),
                           (19,'Eléctrico con estilo y tecnología avanzada.',201,'https://s1.cdn.autoevolution.com/images/news/gallery/examining-the-all-new-q4-e-trons-available-powertrains-and-the-tech-behind-them_8.jpg','Audi',180,'Eléctrico','Audi Q4 e-tron',55000,3,2),
                           (20,'SUV eléctrico con gran autonomía y rendimiento.',346,'https://media.autoexpress.co.uk/image/private/s--IofBDo_C--/v1575319158/autoexpress/2019/11/ford_mustang_mach-e_04_1.jpg','Ford',180,'Eléctrico','Ford Mustang Mach-E',60000,3,2),
                           (21,'Eléctrico de lujo con un diseño impresionante.',516,'https://www.electrichybridvehicletechnology.com/wp-content/uploads/2021/06/P90422119-highRes.jpg','BMW',200,'Eléctrico','BMW iX',70000,3,2),
                           (22,'SUV eléctrico con diseño futurista y gran rendimiento.',302,'https://cdn.motor1.com/images/mgl/XxEO9/s3/hyundai-ioniq-5-right-hand-drive.jpg','Hyundai',185,'Eléctrico','Hyundai Ioniq 5',48000,3,2),
                           (23,'Deportivo de alto rendimiento y diseño aerodinámico.',710,'http://www.hdcarwallpapers.com/walls/mclaren_720s_coupe_2017_2-HD.jpg','McLaren',341,'V8 Twin-Turbo','McLaren 720S',300000,2,3),
                           (24,'Deportivo italiano con diseño llamativo y motor potente.',610,'http://www.autoguide.com/blog/wp-content/uploads/2016/08/2016-Lamborghini-Huracan-LP-610-4-Spyder-Review-5.jpg','Lamborghini',325,'V10','Lamborghini Huracán',250000,2,3),
                           (25,'Deportivo británico de lujo con rendimiento sin igual.',503,'https://abbhbhjlqr.cloudimg.io/images.autodaily.com.au/2021/06/Aston-Martin-Vantage-F1-Edition-7.jpg?w=2520','Aston Martin',314,'V8 Twin-Turbo','Aston Martin Vantage',175000,2,3),
                           (26,'Deportivo estadounidense con un diseño agresivo y un motor V8.',495,'https://photo-voiture.motorlegend.com/hd/chevrolet-corvette-c7-stingray-coupe-6-2-v8-466ch-91384.jpg','Chevrolet',296,'V8','Chevrolet Corvette Stingray',65000,2,3),
                           (27,'De lujo con tecnología avanzada y comodidad excepcional.',523,'https://media.whatcar.com/wc-image/2019-01/2019_bmw_7_series_front.jpg','BMW',250,'Híbrido','BMW 7 Series',90000,3,5),
                           (28,'De lujo con un rendimiento de alta gama y un diseño impresionante.',550,'https://www.automobilesreview.com/gallery/2017-porsche-panamera/2017-porsche-panamera-05.jpg','Porsche',310,'V8 Twin-Turbo','Porsche Panamera',120000,3,5),
                           (29,'Berlina de lujo con un diseño elegante y un interior lujoso.',340,'http://momentcar.com/images/jaguar-xj-super-v8-1.jpg','Jaguar',250,'V6 Supercharged','Jaguar XJ',95000,3,5),
                           (30,'De lujo con un rendimiento excepcional y un diseño único.',580,'https://cevpu.com/wp-content/uploads/2017/01/2017-Maserati-Quattroporte-GTS-GranSport-exterior-front-and-side.jpg','Maserati',310,'V8 Twin-Turbo','Maserati Quattroporte',120000,3,5);
-- Creacion de ratings
INSERT INTO `ratings` VALUES
                          (1,'El coche es increíble, tiene un diseño moderno y los acabados interiores son de alta calidad. El motor responde perfectamente y es muy eficiente en cuanto al consumo de combustible. Sin duda, lo recomendaría a cualquiera que esté buscando un coche confiable y elegante.','2020-06-15 00:00:00.000000','Ana',4.5,1),
                          (2,'Es un coche aceptable, pero los materiales del interior parecen algo baratos para el precio que tiene. Además, he notado que el consumo de gasolina es más alto de lo que se indica en la ficha técnica. Aun así, cumple su función para el día a día.','2021-03-10 00:00:00.000000','José',3,1),
                          (3,'¡Estoy encantado con mi compra! Este coche es una maravilla. Es espacioso, cómodo y tiene muchísima tecnología integrada. Los sensores y asistentes de conducción funcionan de maravilla, y la conducción es suave incluso en carreteras complicadas. Lo volvería a comprar sin dudarlo.','2022-09-25 00:00:00.000000','Carlos',5,2),
                          (4,'Me llevé una decepción con este coche. Aunque el diseño exterior es atractivo, la mecánica no cumple con mis expectativas. Ya tuve que llevarlo al taller dos veces en menos de tres meses por problemas eléctricos. No lo recomendaría.','2023-04-05 00:00:00.000000','María',2,2),
                          (5,'Es una excelente opción por el precio. El motor responde bien en ciudad y en carretera, y el sistema de sonido es sorprendentemente bueno. No es un coche de lujo, pero ofrece mucho por lo que cuesta. Perfecto para una familia pequeña.','2024-01-12 00:00:00.000000','Sofía',4,3),
                          (6,'Terrible experiencia. El coche llegó con un rayón en la pintura y las ruedas desalineadas. Además, la atención al cliente del concesionario fue muy deficiente. No recomendaría este modelo ni esta marca a nadie.','2020-11-20 00:00:00.000000','Javier',1,3),
                          (7,'El coche está bien, pero esperaba más. La conducción es cómoda, pero el espacio en el maletero es menor de lo que esperaba. También me ha decepcionado el sistema de navegación, que parece anticuado comparado con otros modelos del mercado.','2021-07-15 00:00:00.000000','Raúl',3.5,4),
                          (8,'Este coche supera todas mis expectativas. Es potente, eficiente y muy cómodo para largos viajes. Además, los asientos son ergonómicos y no te cansas incluso después de conducir durante horas. Definitivamente lo recomendaría para quienes busquen calidad y confort.','2023-05-22 00:00:00.000000','Elena',4.8,4),
                          (9,'El coche está bien en general, pero he notado que la suspensión no es muy buena en carreteras con baches. Aparte de eso, el diseño y la tecnología son bastante buenos. Es una opción decente, pero tiene margen de mejora.','2022-02-18 00:00:00.000000','Luis',3,5),
                          (10,'¡Perfecto en todos los sentidos! Este coche tiene todo lo que se puede pedir: un diseño espectacular, un interior lleno de detalles de lujo y un motor que es una auténtica joya. La experiencia de conducción es insuperable. Estoy encantado con mi compra.','2024-12-05 00:00:00.000000','Carmen',5,5);

INSERT INTO `app_users` VALUES
                            (1,'Rodrigo','Franco','rodrigofrancocid@gmail.com','rodrigo');